baseURL = "https://blog.sizzlinglikeasausage.com/"
languageCode = "en-us"
title = "Sizzling Like a Sausage"
theme = "mini"
disqusShortname = "allthepaws"

[params]
  author = "Shaz"
  showReadingTime = true
  enableComments = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

