baseURL = "https://example.com/"
languageCode = "en-us"
title = "Sizzling Like a Sausage"
theme = "mini"

[params]
  author = "You"
  showReadingTime = true
  social = true
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
